### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [gacallea/elm-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by gacallea** [comment]
hey @unixorn :)

I'd be honored to be featured! Thanks, I appreciate.

I'll add a screenshot and a license and get back to you.

**Comment by gacallea** [comment]
done :)

thank you for your interest. I never would have thought someone could like this theme.

feel free to reopen the issue if I missed something

**Comment by gacallea** [comment]
now that I think of it, please let me know once it's published and close this issue with the link perhaps? :)

thank you again.
